# Generated by Django 3.0.5 on 2020-04-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail_Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=32)),
                ('domain', models.TextField()),
                ('probed', models.TextField()),
                ('d_type', models.CharField(max_length=10)),
                ('change_to', models.TextField()),
                ('state', models.TextField()),
                ('frequency', models.IntegerField()),
            ],
            options={
                'db_table': 'Mail_Records',
            },
        ),
        migrations.CreateModel(
            name='Session_Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=32)),
                ('switch', models.CharField(max_length=10)),
                ('domain', models.TextField()),
            ],
            options={
                'db_table': 'Session_Mail',
            },
        ),
    ]
